/*
    File:    lynx_scaner_keyword_table.cpp
    Created: 09 February 2019 at 15:18 Moscow time
    Author:  Гаврилов Владимир Сергеевич
    E-mails: vladimir.s.gavrilov@gmail.com
             gavrilov.vladimir.s@mail.ru
             gavvs1977@yandex.ru
*/

#include "../include/cats_scaner_keyword_table.h"

namespace cats_scanner{
    const trans_table::Elem<Lexem_code> keywords_jump_table[] = {
        {const_cast<char32_t*>(U"ео"),   Lexem_code::Id,                 1}, // 0:   б...
        {const_cast<char32_t*>(U"з"),    Lexem_code::Id,                 3}, // 1:   бе...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,                 8}, // 2:   бо...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,                 13}, // 3:   без...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,                 18}, // 4:   бол...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,                 21}, // 5:   безз...
        {const_cast<char32_t*>(U""),    Lexem_code::Kw_vozvrat,          0}, // 6:   боль...
        
        {const_cast<char32_t*>(U"хдйб"),    Lexem_code::Id,              2}, // 8:   больш...
        {const_cast<char32_t*>(U"б"),   Lexem_code::Id,                  4}, // 9:   беззн1...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                 9}, // 10:  беззн3...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,                14}, // 11:  беззн6...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                19}, // 13:  большо...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_viberi,          0}, // 12:  беззн8
        
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,                10}, // 14:  беззн12...
        {const_cast<char32_t*>(U"и"),     Lexem_code::Id,               15}, // 15:  беззн16
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_viudi,           0}, // 16:  беззн32
        

        {const_cast<char32_t*>(U"е"),  Lexem_code::Id,                11}, // 0:  в...
        {const_cast<char32_t*>(U"л"),   Lexem_code::Id,                16}, // 1:  во...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                20}
        {const_cast<char32_t*>(U"т"),  Lexem_code::Id,                22}, // 0:  в...
        {const_cast<char32_t*>(U"ь"),   Lexem_code::Id,                23}, // 1:  во...
        {const_cast<char32_t*>(U""),    Lexem_code::Kw_videlit           0}
             
            
        {const_cast<char32_t*>(U"х"),  Lexem_code::Id,                7}, // 0:  в...
        {const_cast<char32_t*>(U"о"),   Lexem_code::Id,                12}, // 1:  во...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,                17}
        {const_cast<char32_t*>(U""),    Lexem_code::Kw_videlit           0}
             
     
        {const_cast<char32_t*>(U"л"),  Lexem_code::Id,                25}, // 0:  в...
        {const_cast<char32_t*>(U"а"),   Lexem_code::Id,                26}, // 1:  во...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,                27}
        {const_cast<char32_t*>(U"н"),  Lexem_code::Id,                28}, // 0:  в...
        {const_cast<char32_t*>(U"а"),   Lexem_code::Id,                29}, // 1:  во...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,                30}
        {const_cast<char32_t*>(U""),    Lexem_code::Kw_glavnya           0}
             
         {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                32}, // 64:  д...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,                33}, // 65:  дл...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_dlya,            0}, // 66:  для
        
         {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                35}, // 67:  е...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                36}, // 68:  ес...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                37}, // 69:  есл...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_esli,            0}, // 70:  если

             
        {const_cast<char32_t*>(U"з"),  Lexem_code::Id,                38}, // 23:  вы...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,                39}, // 24:  веч...
        {const_cast<char32_t*>(U"а"), Lexem_code::Id,                40}, // 25:  вещ...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,                41}, // 26:  воз...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,                42}, // 27:  выб...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                43}, // 28:  выд...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,                44}, // 28:  выд...
        {const_cast<char32_t*>(U""),    Lexem_code::Kw_znakno,         0}, // 29:  вый...
        {const_cast<char32_t*>(U"1368"),    Lexem_code::Id,                45}, // 30:  вечн...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                49}, // 31:  вещ1...
        {const_cast<char32_t*>(U"8"),    Lexem_code::Id,                53}, // 32:  вещ3...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_znakno128,       0}, // 48:  вещ128
        
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                51}, // 33:  вещ6...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_znakno32,       0}, // 48:  вещ128
        
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,                52}, // 34:  вещ8...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_znakno64,       0}, // 48:  вещ128
        
        {const_cast<char32_t*>(U""),    Lexem_code::Kw_znakno8,                48}, // 35:  возв...
        
        
        
           {const_cast<char32_t*>(U"н"),   Lexem_code::Id,                55}, // 71:  и...
        {const_cast<char32_t*>(U"ае"),   Lexem_code::Id,                56}, // 72:  ин...
        {const_cast<char32_t*>(U"ч"),    Lexem_code::Id,                58}, // 73:  ис...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                60}, // 74:  ина...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Kw_inache,          0}, // 74:  ина...
        
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                59}, // 75:  ине...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Kw_inache,          0}, // 74:  ина...
        
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                62}, // 76:  ист...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,                63}, // 77:  инач...
        {const_cast<char32_t*>(U"с"),     Lexem_code::Id,               64}, // 78:  инес
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,                65}, // 79:  исти...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_const,          0}, // 82:  истина

        
        
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                67}, // 37:  выде...
        {const_cast<char32_t*>(U"г"),    Lexem_code::Id,                68}, // 38:  выйд...
        {const_cast<char32_t*>(U"и"),     Lexem_code::Id,                69}, // 39:  вечно
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,                70}, // 40:  вещ12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_logic,          0}, // 82:  истина
         {const_cast<char32_t*>(U""),     Lexem_code::Kw_logic8,          0}, // 82:  истина
         
        {const_cast<char32_t*>(U"1368"),    Lexem_code::Id,                71}, // 44:  возвр...
        {const_cast<char32_t*>(U"6"),    Lexem_code::Id,                75}, // 45:  выбер...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_logic16,           0}, // 47:  выйди
        
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,                76}, // 46:  выдел...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_logic32,           0}, // 47:  выйди
        
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,                77}, // 44:  возвр...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_logic64,           0}, // 47:  выйди
        
        {const_cast<char32_t*>(U"ао"),    Lexem_code::Id,                79}, // 45:  выбер...
        {const_cast<char32_t*>(U"кс"),    Lexem_code::Id,               81}, // 46:  выдел...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                84}, // 49:  возвра...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_max,           0}, // 47:  выйди
       
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,                83}, // 51:  выделе...
        {const_cast<char32_t*>(U"у"),    Lexem_code::Id,                86}, // 53:  выделен...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,                88}, // 54:  выделени...
        {const_cast<char32_t*>(U"ь"),    Lexem_code::Id,                90}, // 54:  выделени...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_modul,           0}, // 55:  выделение
     
        {const_cast<char32_t*>(U"с"),   Lexem_code::Id,                85}, // 72:  ин...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                87}, // 73:  ис...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,                89}, // 74:  ина...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_massiv,            0}, // 78:  инес
        
        {const_cast<char32_t*>(U"ае"),    Lexem_code::Id,                92}, // 75:  ине...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,                94}, // 76:  ист...
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                97}, // 77:  инач...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,                100}, // 79:  исти...
        {const_cast<char32_t*>(U"г"),    Lexem_code::Id,                102}, // 81:  истин...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,                104}, // 77:  инач...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,                106}, // 79:  исти...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_navsegda,          0}, // 82:  истина

        {const_cast<char32_t*>(U"п"),    Lexem_code::Id,                95}, // 83:  к...
        {const_cast<char32_t*>(U"тр"),   Lexem_code::Id,                98}, // 84:  ко...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,                101}, // 85:  ком...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,                103}, // 86:  кон...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,                105}, // 87:  комп...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,                107}, // 88:  конс...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_nepravda,        0}, // 99:  компл128

        
        {const_cast<char32_t*>(U"у"), Lexem_code::Id,          99}, // 89:  компл...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_netu,           0}, // 90:  конст...
        
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,                109}, // 91:  компл1...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,                110}, // 92:  компл3...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                111}, // 93:  компл6...
        {const_cast<char32_t*>(U"б"),    Lexem_code::Id,                112}, // 94:  компл8...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,                113}, // 95:  компл12...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,                114}, // 94:  компл8...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,                115}, // 95:  компл12...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,                116}, // 94:  компл8...
        {const_cast<char32_t*>(U"ь"),    Lexem_code::Id,                117}, // 95:  компл12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_osvobodit,         0}, // 96:  компл32
        

        {const_cast<char32_t*>(U"еору"),    Lexem_code::Id,               119}, // 100: л...
        {const_cast<char32_t*>(U"р"),   Lexem_code::Id,               125}, // 101: ло...
        {const_cast<char32_t*>(U"е"), Lexem_code::Kw_log,           130}, // 102: лог...
        {const_cast<char32_t*>(U"мйк"),    Lexem_code::Id,               136}, // 103: лож...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,               143}, // 104: лог1...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               147}, // 105: лог3...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,               151}, // 106: лог6...
        {const_cast<char32_t*>(U"а"),     Lexem_code::Id,               155}, // 107: лог8
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_goto,            0}, // 108: ложь
        
        {const_cast<char32_t*>(U"м"),     Lexem_code::Id,               138}, // 107: лог8
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_perem,           0}, // 110: лог3
        
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               123}, // 131: ни...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,               128}, // 132: нич...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,               134}, // 133: ничт...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               141}, // 132: нич...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_pravda,          0}, // 134: ничто
        
        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,               124}, // 135: о...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,               129}, // 136: ос...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               135}, // 137: осв...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,               142}, // 138: осво...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_pustaya,   0}, // 146: освобождение...

        {const_cast<char32_t*>(U"л"),   Lexem_code::Id,               137}, // 112: м...
        {const_cast<char32_t*>(U"ю"),   Lexem_code::Id,               144}, // 113: ма...
        {const_cast<char32_t*>(U"ч"),    Lexem_code::Id,               148}, // 114: мо...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               152}, // 115: мал...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               156}, // 115: мал...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_perekluchi,        0}, // 129: маленькое
        
         {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               139}, // 123: модул...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               145}, // 124: малень...
        {const_cast<char32_t*>(U"ь"),     Lexem_code::Id,          149}, // 125: массив
        {const_cast<char32_t*>(U"к"),     Lexem_code::Id,          153}, // 126: модуль
        {const_cast<char32_t*>(U"у"),    Lexem_code::Id,               157}, // 127: маленьк...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_poskolky,        0}, // 129: маленькое

        
        {const_cast<char32_t*>(U"кс"),    Lexem_code::Id,               126}, // 116: мас...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               133}, // 117: мод...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_poka,        0}, // 129: маленькое
           
        {const_cast<char32_t*>(U"лк"),    Lexem_code::Id,               131}, // 118: мале...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               140}, // 119: масс...
        {const_cast<char32_t*>(U"д"),    Lexem_code::Id,               176}, // 120: моду...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               180}, // 121: мален...
        {const_cast<char32_t*>(U"в"),    Lexem_code::Id,               184}, // 122: масси...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_posledov,        0}, // 129: маленькое
        
        {const_cast<char32_t*>(U"ае"),    Lexem_code::Id,               159}, // 135: о...
        {const_cast<char32_t*>(U"з"),    Lexem_code::Id,               161}, // 136: ос...
        {const_cast<char32_t*>(U"б"),    Lexem_code::Id,               163}, // 137: осв...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               165}, // 138: осво...
        {const_cast<char32_t*>(U"р"),    Lexem_code::Id,               167}, // 137: осв...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_razb,   0}, // 146: освобождение...

        {const_cast<char32_t*>(U"п"),   Lexem_code::Id,               162}, // 147: п...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               164}, // 148: пе...
        {const_cast<char32_t*>(U"т"),   Lexem_code::Id,               166}, // 149: по...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_repit,       0}, // 167: повторяй
        
        {const_cast<char32_t*>(U"т1368лмс"),   Lexem_code::Id,               169}, // 152: пок...
        {const_cast<char32_t*>(U"р"),   Lexem_code::Id,               177}, // 153: пере...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               185}, // 154: повт...
        {const_cast<char32_t*>(U"к"),     Lexem_code::Id,            190}, // 155: пока
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,               193}, // 156: поку...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_struct,           0}, // 157: перем
        
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,               178}, // 158: переч...
        {const_cast<char32_t*>(U"8"),    Lexem_code::Id,               186}, // 159: повто...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_c128,          0}, // 163: покуда
        
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,               179}, // 160: покуд...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_c32,          0}, // 163: покуда
        
        {const_cast<char32_t*>(U"4"),    Lexem_code::Id,               180}, // 161: перечи...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_c64,          0}, // 163: покуда
        
        {const_cast<char32_t*>(U"0"),    Lexem_code::Id,               181}, // 162: повтор...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_c80,          0}, // 163: покуда
    
        {const_cast<char32_t*>(U"у"),    Lexem_code::Id,               182}, // 164: перечис...
        {const_cast<char32_t*>(U"ч"),    Lexem_code::Id,               187}, // 165: повторя...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               191}, // 166: перечисл...
        {const_cast<char32_t*>(U"й"),    Lexem_code::Id,               194}, // 168: перечисле...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_slychay,          0}, // 163: покуда
        
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               183}, // 169: перечислен...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               188}, // 170: перечислени...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_smol,   0}, // 171: перечисление

        {const_cast<char32_t*>(U"с"),    Lexem_code::Id,               176}, // 172: р...
        {const_cast<char32_t*>(U"ы"),    Lexem_code::Id,               184}, // 173: ра...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               189}, // 174: раз...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,               192}, // 175: разб...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               195}, // 176: разбо...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_ssilka,          0}, // 177: разбор

        {const_cast<char32_t*>(U"ио"),  Lexem_code::Id,               197}, // 178: с...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_to,            0}, // 185: симв
        
        {const_cast<char32_t*>(U"п"),    Lexem_code::Id,               199}, // 180: сс...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_tip,            0}, // 185: симв
        
        {const_cast<char32_t*>(U"м"),    Lexem_code::Id,               201}, // 181: ст...
        {const_cast<char32_t*>(U"о"),    Lexem_code::Id,               202}, // 182: сим...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               203}, // 183: ссы...
        {const_cast<char32_t*>(U"ч"),   Lexem_code::Id,               204}, // 184: стр...
        {const_cast<char32_t*>(U"а"),    Lexem_code::Id,               205}, // 186: ссыл...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,               206}, // 187: стро...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               207}, // 188: стру...
        {const_cast<char32_t*>(U"ю"),    Lexem_code::Id,               208}, // 189: ссылк...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_ymolchaniy,     0}, // 185: симв
        
        {const_cast<char32_t*>(U"у"),    Lexem_code::Id,               210}, // 190: строк...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,               211}, // 191: струк...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,               212}, // 194: структ...
        {const_cast<char32_t*>(U"ц"),    Lexem_code::Id,               213}, // 195: структу...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               214}, // 196: структур...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,               215}, // 196: структур.
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_funcsia,       0}, // 197: структура

        {const_cast<char32_t*>(U"у"),    Lexem_code::Id,               203}, // 202: ф...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,               204}, // 203: фу...
        {const_cast<char32_t*>(U"к"),    Lexem_code::Id,               205}, // 204: фун...
        {const_cast<char32_t*>(U"ц"),    Lexem_code::Id,               206}, // 205: функ...
        {const_cast<char32_t*>(U"и"),    Lexem_code::Id,               207}, // 206: функц...
        {const_cast<char32_t*>(U"я"),    Lexem_code::Id,               208}, // 207: функци...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_funktsiya,       0}, // 208: функция

        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               217}, // 209: ц...
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               218}, // 210: це...
        {const_cast<char32_t*>(U"в"), Lexem_code::Kw_tsel,          219}, // 211: цел...
        {const_cast<char32_t*>(U"е"),   Lexem_code::Id,               220}, // 212: цел1...
        {const_cast<char32_t*>(U"щ"),    Lexem_code::Id,               221}, // 213: цел3...
        {const_cast<char32_t*>(U""),     Lexem_code::Kv_z,           0}, // 215: цел8
        
        {const_cast<char32_t*>(U"1368"),    Lexem_code::Id,               257}, // 214: цел6...
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,               261}, // 216: цел12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_z128,           0}, // 215: цел8
        
        {const_cast<char32_t*>(U"2"),    Lexem_code::Id,               228}, // 216: цел12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_z32,          0}, // 217: цел16
        
         {const_cast<char32_t*>(U"0"),    Lexem_code::Id,               229}, // 216: цел12...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_z80,          0}, // 217: цел16
     
     
        {const_cast<char32_t*>(U"л"),    Lexem_code::Id,               231}, // 221: ч...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               232}, // 222: чи...
        {const_cast<char32_t*>(U"м"),    Lexem_code::Id,               233}, // 223: чис...
        {const_cast<char32_t*>(U"е"),    Lexem_code::Id,               234}, // 222: чи...
        {const_cast<char32_t*>(U"н"),    Lexem_code::Id,               235}, // 224: чист...
        {const_cast<char32_t*>(U"т"),    Lexem_code::Id,               236}, // 225: чиста...
        {const_cast<char32_t*>(U""),     Lexem_code::Kw_element,        0}  // 226: чистая
    };
};




