/*
    File:    lynx_scaner_keyword_table.cpp
    Created: 09 February 2019 at 15:18 Moscow time
    Author:  Гаврилов Владимир Сергеевич
    E-mails: vladimir.s.gavrilov@gmail.com
             gavrilov.vladimir.s@mail.ru
             gavvs1977@yandex.ru
*/

#include "../include/cats_scaner_keyword_table.h"

namespace cats_scanner{
    const trans_table::Elem<Lexem_code> keywords_jump_table[] = {
        

        

{const_cast<char32_t*>(U"оы"), Lexem_code::Id, 1}, // 0: в... 
{const_cast<char32_t*>(U"з"), Lexem_code::Id, 3}, // 1: во... 
{const_cast<char32_t*>(U"бдйх"), Lexem_code::Id, 4}, // 2: вы... 
{const_cast<char32_t*>(U"в"), Lexem_code::Id, 8}, // 3: воз... 
{const_cast<char32_t*>(U"е"), Lexem_code::Id, 9}, // 4: выб... 
{const_cast<char32_t*>(U"е"), Lexem_code::Id, 10}, // 5: выд... 
{const_cast<char32_t*>(U"д"), Lexem_code::Id, 11}, // 6: вый... 
{const_cast<char32_t*>(U"о"), Lexem_code::Id, 12}, // 7: вых... 
{const_cast<char32_t*>(U"р"), Lexem_code::Id, 13}, // 8: возв... 
{const_cast<char32_t*>(U"р"), Lexem_code::Id, 14}, // 9: выбе... 
{const_cast<char32_t*>(U"л"), Lexem_code::Id, 15}, // 10: выде... 
{const_cast<char32_t*>(U"и"), Lexem_code::Id, 16}, // 11: выйд... 
{const_cast<char32_t*>(U"д"), Lexem_code::Id, 17}, // 12: выхо... 
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 18}, // 13: возвр... 
{const_cast<char32_t*>(U"и"), Lexem_code::Id, 19}, // 14: выбер... 
{const_cast<char32_t*>(U"и"), Lexem_code::Id, 20}, // 15: выдел... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_viudi, 0}, // 16: выйди 
{const_cast<char32_t*>(U""), Lexem_code::Kw_exit, 0}, // 17: выход 
{const_cast<char32_t*>(U"т"), Lexem_code::Id, 21}, // 18: возвра... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_viberi, 0}, // 19: выбери 
{const_cast<char32_t*>(U"т"), Lexem_code::Id, 22}, // 20: выдели...
{const_cast<char32_t*>(U""), Lexem_code::Kw_vozvrat, 0}, // 21: возврат 
{const_cast<char32_t*>(U"ь"), Lexem_code::Id, 23}, // 22: выделит... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_videlit, 0}, // 23: выделить
             

     {const_cast<char32_t*>(U"л"), Lexem_code::Id, 25}, // 24: г... 
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 26}, // 25: гл... 
{const_cast<char32_t*>(U"в"), Lexem_code::Id, 27}, // 26: гла... 
{const_cast<char32_t*>(U"н"), Lexem_code::Id, 28}, // 27: глав... 
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 29}, // 28: главн... 
{const_cast<char32_t*>(U"я"), Lexem_code::Id, 30}, // 29: главна... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_glavnya, 0}, // 30: 
             
        {const_cast<char32_t*>(U"л"), Lexem_code::Id, 32}, // 31: д... 
{const_cast<char32_t*>(U"я"), Lexem_code::Id, 33}, // 32: дл... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_dla, 0}, // 33: для

{const_cast<char32_t*>(U"с"), Lexem_code::Id, 35}, // 34: е... 
{const_cast<char32_t*>(U"л"), Lexem_code::Id, 36}, // 35: ес... 
{const_cast<char32_t*>(U"и"), Lexem_code::Id, 37}, // 36: есл... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_esli, 0}, // 37: если
 
{const_cast<char32_t*>(U"н"), Lexem_code::Id, 39}, // 38: з... 
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 40}, // 39: зн... 
{const_cast<char32_t*>(U"к"), Lexem_code::Id, 41}, // 40: зна... 
{const_cast<char32_t*>(U"н"), Lexem_code::Id, 42}, // 41: знак... 
{const_cast<char32_t*>(U"е"), Lexem_code::Id, 43}, // 42: знакн... 
{const_cast<char32_t*>(U"т"), Lexem_code::Id, 44}, // 43: знакне... 
{const_cast<char32_t*>(U"1368"), Lexem_code::Kw_znakno, 45}, // 44: знакнет... 
{const_cast<char32_t*>(U"26"), Lexem_code::Id, 49}, // 45: знакнет1... 
{const_cast<char32_t*>(U"2"), Lexem_code::Id, 51}, // 46: знакнет3... 
{const_cast<char32_t*>(U"4"), Lexem_code::Id, 52}, // 47: знакнет6... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_znakno8, 0}, // 48: знакнет8 
{const_cast<char32_t*>(U"8"), Lexem_code::Id, 53}, // 49: знакнет12... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_znakno16, 0}, // 50: знакнет16 
{const_cast<char32_t*>(U""), Lexem_code::Kw_znakno32, 0}, // 51: знакнет32 
{const_cast<char32_t*>(U""), Lexem_code::Kw_znakno64, 0}, // 52: знакнет64 
{const_cast<char32_t*>(U""), Lexem_code::Kw_znakno128, 0}, // 53: знакнет128
        
        {const_cast<char32_t*>(U"н"), Lexem_code::Id, 55}, // 54: и... 
{const_cast<char32_t*>(U"ае"), Lexem_code::Id, 56}, // 55: ин... 
{const_cast<char32_t*>(U"ч"), Lexem_code::Id, 58}, // 56: ина... 
{const_cast<char32_t*>(U"с"), Lexem_code::Id, 59}, // 57: ине... 
{const_cast<char32_t*>(U"е"), Lexem_code::Id, 60}, // 58: инач... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_ines, 0}, // 59: инес
{const_cast<char32_t*>(U""), Lexem_code::Kw_inache, 0}, // 60: 

{const_cast<char32_t*>(U"о"), Lexem_code::Id, 62}, // 61: к... 
{const_cast<char32_t*>(U"н"), Lexem_code::Id, 63}, // 62: ко... 
{const_cast<char32_t*>(U"с"), Lexem_code::Id, 64}, // 63: кон... 
{const_cast<char32_t*>(U"т"), Lexem_code::Id, 65}, // 64: конс... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_const, 0}, // 65: 

{const_cast<char32_t*>(U"о"), Lexem_code::Id, 67}, // 66: л... 
{const_cast<char32_t*>(U"г"), Lexem_code::Id, 68}, // 67: ло... 
{const_cast<char32_t*>(U"и"), Lexem_code::Id, 69}, // 68: лог... 
{const_cast<char32_t*>(U"к"), Lexem_code::Id, 70}, // 69: логи... 
{const_cast<char32_t*>(U"1368"), Lexem_code::Kw_logic, 71}, // 70: логик... 
{const_cast<char32_t*>(U"6"), Lexem_code::Id, 75}, // 71: логик1... 
{const_cast<char32_t*>(U"2"), Lexem_code::Id, 76}, // 72: логик3... 
{const_cast<char32_t*>(U"4"), Lexem_code::Id, 77}, // 73: логик6... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_logic8, 0}, // 74: логик8 
{const_cast<char32_t*>(U""), Lexem_code::Kw_logic16, 0}, // 75: логик16 
{const_cast<char32_t*>(U""), Lexem_code::Kw_logic32, 0}, // 76: логик32 
{const_cast<char32_t*>(U""), Lexem_code::Kw_logic64, 0}, // 77: логик64

{const_cast<char32_t*>(U"ао"), Lexem_code::Id, 79}, // 78: м... 
{const_cast<char32_t*>(U"кс"), Lexem_code::Id, 81}, // 79: ма... 
{const_cast<char32_t*>(U"д"), Lexem_code::Id, 83}, // 80: мо... 
{const_cast<char32_t*>(U"с"), Lexem_code::Id, 84}, // 81: мак... 
{const_cast<char32_t*>(U"с"), Lexem_code::Id, 85}, // 82: мас... 
{const_cast<char32_t*>(U"у"), Lexem_code::Id, 86}, // 83: мод... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_max, 0}, // 84: макс 
{const_cast<char32_t*>(U"и"), Lexem_code::Id, 87}, // 85: масс... 
{const_cast<char32_t*>(U"л"), Lexem_code::Id, 88}, // 86: моду... 
{const_cast<char32_t*>(U"в"), Lexem_code::Id, 89}, // 87: масси... 
{const_cast<char32_t*>(U"ь"), Lexem_code::Id, 90}, // 88: модул... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_massiv, 0}, // 89: массив 
{const_cast<char32_t*>(U""), Lexem_code::Kw_modul, 0}, // 90: модуль

{const_cast<char32_t*>(U"ае"), Lexem_code::Id, 92}, // 91: н... 
{const_cast<char32_t*>(U"в"), Lexem_code::Id, 94}, // 92: на... 
{const_cast<char32_t*>(U"пт"), Lexem_code::Id, 95}, // 93: не... 
{const_cast<char32_t*>(U"с"), Lexem_code::Id, 97}, // 94: нав... 
{const_cast<char32_t*>(U"р"), Lexem_code::Id, 98}, // 95: неп... 
{const_cast<char32_t*>(U"у"), Lexem_code::Id, 99}, // 96: нет... 
{const_cast<char32_t*>(U"е"), Lexem_code::Id, 100}, // 97: навс... 
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 101}, // 98: непр... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_netu, 0}, // 99: нету 
{const_cast<char32_t*>(U"г"), Lexem_code::Id, 102}, // 100: навсе... 
{const_cast<char32_t*>(U"в"), Lexem_code::Id, 103}, // 101: непра... 
{const_cast<char32_t*>(U"д"), Lexem_code::Id, 104}, // 102: навсег... 
{const_cast<char32_t*>(U"д"), Lexem_code::Id, 105}, // 103: неправ... 
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 106}, // 104: навсегд... 
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 107}, // 105: неправд... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_navsegda, 0}, // 106: навсегда 
{const_cast<char32_t*>(U""), Lexem_code::Kw_nepravda, 0}, // 107: неправда

{const_cast<char32_t*>(U"с"), Lexem_code::Id, 109}, // 108: о... 
{const_cast<char32_t*>(U"в"), Lexem_code::Id, 110}, // 109: ос... 
{const_cast<char32_t*>(U"о"), Lexem_code::Id, 111}, // 110: осв... 
{const_cast<char32_t*>(U"б"), Lexem_code::Id, 112}, // 111: осво... 
{const_cast<char32_t*>(U"о"), Lexem_code::Id, 113}, // 112: освоб... 
{const_cast<char32_t*>(U"д"), Lexem_code::Id, 114}, // 113: освобо... 
{const_cast<char32_t*>(U"и"), Lexem_code::Id, 115}, // 114: освобод... 
{const_cast<char32_t*>(U"т"), Lexem_code::Id, 116}, // 115: освободи... 
{const_cast<char32_t*>(U"ь"), Lexem_code::Id, 117}, // 116: освободит... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_osvobodit, 0}, // 117: освободить

{const_cast<char32_t*>(U"еору"), Lexem_code::Id, 119}, // 118: п...
{const_cast<char32_t*>(U"р"), Lexem_code::Id, 123}, // 119: пе... 
{const_cast<char32_t*>(U"кс"), Lexem_code::Id, 124}, // 120: по... 
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 126}, // 121: пр... 
{const_cast<char32_t*>(U"с"), Lexem_code::Id, 127}, // 122: пу... 
{const_cast<char32_t*>(U"е"), Lexem_code::Id, 128}, // 123: пер... 
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 129}, // 124: пок... 
{const_cast<char32_t*>(U"л"), Lexem_code::Id, 130}, // 125: пос... 
{const_cast<char32_t*>(U"в"), Lexem_code::Id, 131}, // 126: пра... 
{const_cast<char32_t*>(U"т"), Lexem_code::Id, 132}, // 127: пус... 
{const_cast<char32_t*>(U"йкм"), Lexem_code::Id, 133}, // 128: пере... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_poka, 0}, // 129: пока 
{const_cast<char32_t*>(U"е"), Lexem_code::Id, 136}, // 130: посл... 
{const_cast<char32_t*>(U"д"), Lexem_code::Id, 137}, // 131: прав...
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 138}, // 132: пуст... 
{const_cast<char32_t*>(U"д"), Lexem_code::Id, 139}, // 133: перей... 
{const_cast<char32_t*>(U"л"), Lexem_code::Id, 140}, // 134: перек... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_perem, 0}, // 135: перем 
{const_cast<char32_t*>(U"д"), Lexem_code::Id, 141}, // 136: после... 
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 142}, // 137: правд... 
{const_cast<char32_t*>(U"я"), Lexem_code::Id, 143}, // 138: пуста... 
{const_cast<char32_t*>(U"и"), Lexem_code::Id, 144}, // 139: перейд... 
{const_cast<char32_t*>(U"ю"), Lexem_code::Id, 145}, // 140: перекл... 
{const_cast<char32_t*>(U"о"), Lexem_code::Id, 146}, // 141: послед... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_pravda, 0}, // 142: правда 
{const_cast<char32_t*>(U""), Lexem_code::Kw_pustaya, 0}, // 143: пустая 
{const_cast<char32_t*>(U"н"), Lexem_code::Id, 147}, // 144: перейди... 
{const_cast<char32_t*>(U"ч"), Lexem_code::Id, 148}, // 145: переклю... 
{const_cast<char32_t*>(U"в"), Lexem_code::Id, 149}, // 146: последо... 
{const_cast<char32_t*>(U"а"), Lexem_code::Id, 150}, // 147: перейдин... 
{const_cast<char32_t*>(U"и"), Lexem_code::Id, 151}, // 148: переключ... 
{const_cast<char32_t*>(U""), Lexem_code::Kw_posledov, 0}, // 149: последов 
{const_cast<char32_t*>(U""), Lexem_code::Kw_goto, 0}, // 150: перейдина 
{const_cast<char32_t*>(U""), Lexem_code::Kw_perekluchi, 0}, // 151: переключи
     
    };
};




